### ISSUE TITLE
filenames not visible in tabs

### ISSUE THREAD

**Issue by rcrooks** [arturoalviar/atom-kecleon-ui#1]
Hi, nice theme, but filenames in tabs seem to be the same color as the background, and so are not visible.

This seems to be the selector:

body > atom-workspace > atom-workspace-axis > atom-workspace-axis > atom-pane-container > atom-pane > ul > li.texteditor.tab.sortable.right-clicked.active > div.title.icon.html5-icon.medium-orange ::before

**Comment by arturoalviar** [comment]
thanks for downloading the theme. I noticed this issue was happening with the file-icons package, is that correct? Anyway, I made an adjustment to the title pseudo element and believe filenames should now be visible.
